### ISSUE TITLE
Design Doc Checklist

### ISSUE THREAD

**Issue by jhnegbrt** [Williamsliam23/Discord_Clone#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a description sentence of the app
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [x] all links route the correct page

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-campus-hybrid/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [ ] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details (primary and foreign keys, not null, indexed, unique)
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [ ] Correctly formatted
    - [x] schema is written in a table format
    - [ ] table names, column names, and foreign keys are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded

---

# Sample State

- [x] State shape is flat!
- [ ] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes

- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

**Comment by jhnegbrt** [comment]
### MVP
- Add bullets (links to pages) on Home page
- A few missing things formatting wise, check bluebird repo and issue above

### Schema
- A couple of formatting issues (see above)
- Add foreign key references beneath tables
- what is the `user_id` column in servers and `channels` for `creator_id` or `owner_id` may be more semantic?
- `messages` doesn't need `server_id` (can you figure out why?)
- You will need additional joins tables (or some other solution) for connecting `users` to `servers` and `channels` and `channels` to `servers`

**Comment by jhnegbrt** [comment]
### Schema
- lowercase your `joins` table
- good job - this table now provides a link between users and their servers
- Do you want it so that if a user is in a server, they will immediately have access to all channels? If you want a Direct Message feature, or the ability to join/leave channels you will need another joins table. If not, this is all good.

### Sample State
- Make sure that your keys are camel cased

### Routes
- work on these as soon as you can
